### PR TITLE
Stay in Touch | Milestone 6 

### PR DESCRIPTION
**Pull request by errea**
# Description
This project is a collaborative project in which on this milestone we were asked to try and implement friendships with 2 rows for mutual friendship [example here](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) && [Another example here]( https://explainextended.com/2009/03/07/selecting-friends/)

Therefore this pull request is to determine that we; 
- [x] implemented the  mutual friendships in the most efficient way
- [x] implemented unit and integrations tests

# How To Enforce standard Guide 
We achieved this with the following:

- [x] Rubocop
- [x] Stylelint
- [x] Test Integration

# Checklist:

- [x] Our code follows the style guidelines of this project
- [x] We performed a self-review of our code
- [x] We commented on my code, particularly in hard-to-understand areas
- [x] We made corresponding changes to the documentation
- [x] We added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally 
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes requested👈
**Hey guys, you have done a good job so far, and I'm impressed, However, there are few issues to fix before we move**💪✔
**What you have done**

- The PR and summary text is really good and professional.
- The Readme file looks good too.
- The code looks clean.

**Changes to make**

- [x]  A user should be able to send a friend request and cancel a request, in this case, I can't cancel a friendship request, fix this.

- [x]  A friend request is sent to a user, but the user can't see it, and no error is being displayed when the same user where a request is sent tries to send a request back.

- [x]  Some tests are failing in user_spec.rb file.

- [x]  The only user to see the posts of a user, is a friendship user.

- [x] When I try to cancel a friend request, I get the error in the image  below
cancel friendship

Please fix the above issues and submit another review request.

_In case you have a question, reach me on slack as Elisha kyakopo_

Cheers

**Comment by Mihndim2020** [comment]
Changes effected as requested. Thank you for your feedback.

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] You have mastered Git Flow.
- [x] README is professional and has all the instructions to run the project locally.
## To Improve 🙏
- [x] User should be able to accept friendship requests to start friendship. The user is unable to accept friendship requests. Please fix that!
- [x] User should only see his posts and posts by his friends. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png).
- [x] Please remove commented code from user model, user show template, friendships controller, and friendships helper.
- [x] Please add Integration tests for friendship functionality. 
- [x] I would suggest you please see all the requirements of this milestone again and make sure everything works fine before asking for another review!

# Optional
- [x] App logic should be separated from views. You have some logic in friendships form partial. KIndly create a helper for it under helpers and move all the logic there.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, Thank you for implementing changes suggested by me previously :ok_hand:

## To Improve 🙏
- [x] Thank you for adding one Integration test for the sign-in feature, but as I pointed out in a previous review you need to add Integration tests for friendship features e.g invite friend, cancel request, accept the request and reject the request.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @errea and @Mihndim2020! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
